//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseFirst
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
	public partial class RecipeOrganizerEntities : DbContext
    {
        public RecipeOrganizerEntities() : base("name=RecipeOrganizerEntities") {}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
    }
}
